### ISSUE TITLE
Underscore dependency not noted

### ISSUE THREAD

**Issue by hhelwich** [detro/jasmine-jsreporter#11]
I think in the Readme it is missing that underscore is needed

**Comment by detro** [comment]
Caused by https://github.com/detro/jasmine-jsreporter/pull/10

I apologise: I should have spotted the dependency.
But I was fooled by the small bits where it's used and the fact that... well, it's an "_".

I though it was a safe patch.

**Comment by hhelwich** [comment]
No problem :-)

**Comment by detro** [comment]
Solved by ca8b7626b7f1061650c394d60021ed867ff802be

**Comment by hhelwich** [comment]
Thanks! :ok_hand:
