### ISSUE TITLE
JSReporter2 is undefined

### ISSUE THREAD

**Issue by steveoh** [detro/jasmine-jsreporter#15]
when adding

`jasmine.getEnv().addReporter(new jasmine.JSReporter2());`

I get an undefined is not a function error. 

Can you put up an example using jasmine 2.0?

---

My [SpecRunner](https://github.com/agrc/fiber-verification/blob/saucy/_SpecRunner.html#L23)
Adding the [Reporter](https://github.com/agrc/fiber-verification/blob/saucy/src/app/tests/jasmineTestBootstrap.js#L21) **this is where the error originates**
The [version of jasmine-jsreporter](https://github.com/agrc/fiber-verification/blob/saucy/bower.json#L16) I am using.

**Comment by alextreppass** [comment]
I wonder if grunt-contrib-jasmine are behind jasmine 2.0 slightly.

If you load Jasmine 2.0's jasmine.js, jasmine-html.js and boot.js before jasmine-jsreporter.js, things should work as expected.

Here's a gist example: https://gist.github.com/alextreppass/7c85fe8e631e978dd6c7

**Comment by detro** [comment]
Is @alextreppass suggestion working?

**Comment by detro** [comment]
I consider this done.

**Comment by stdavis** [comment]
In order for me to get this to work I had to load it like this:

``` javascript
jasmine.getEnv().addReporter(new jasmineRequire.JSReporter2());
```
